{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","kind":"typeIdentifier","text":"AWSErrorContext"},{"text":"?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsservererror\/context"]}],"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context"},"metadata":{"title":"context","role":"symbol","roleHeading":"Instance Property","externalID":"s:8SotoCore14AWSServerErrorV7contextAA15AWSErrorContextVSgvp","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"text":"AWSErrorContext","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"name":"SotoCore"}]},"abstract":[{"type":"text","text":"additional context information related to the error"}],"kind":"symbol","sections":[],"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AWSErrorContext","kind":"identifier"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}],"title":"AWSErrorContext","kind":"symbol","type":"topic","abstract":[{"text":"Additional information about error","type":"text"}],"url":"\/documentation\/sotocore\/awserrorcontext"},"doc://codes.soto.soto-core/documentation/SotoCore":{"abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"title":"SotoCore","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","url":"\/documentation\/sotocore","kind":"symbol","type":"topic","role":"collection"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AWSServerError"}],"abstract":[],"role":"symbol","title":"AWSServerError","url":"\/documentation\/sotocore\/awsservererror","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AWSServerError","kind":"identifier"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/context":{"abstract":[{"type":"text","text":"additional context information related to the error"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"text":"?","kind":"text"}],"title":"context","url":"\/documentation\/sotocore\/awsservererror\/context","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/context"}}}