{"variants":[{"paths":["\/documentation\/sotocore\/awsservererror\/internalfailure"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"modules":[{"name":"SotoCore"}],"role":"symbol","title":"internalFailure","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"internalFailure","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWSServerError","preciseIdentifier":"s:8SotoCore14AWSServerErrorV"}],"externalID":"s:8SotoCore14AWSServerErrorV15internalFailureACvpZ","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"internalFailure","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8SotoCore14AWSServerErrorV","kind":"typeIdentifier","text":"AWSServerError","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"type":"topic","title":"SotoCore","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","url":"\/documentation\/sotocore","role":"collection","kind":"symbol","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/internalFailure":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure","abstract":[],"title":"internalFailure","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalFailure","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWSServerError","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore14AWSServerErrorV"}],"role":"symbol","type":"topic","url":"\/documentation\/sotocore\/awsservererror\/internalfailure","kind":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","title":"AWSServerError","abstract":[],"type":"topic","url":"\/documentation\/sotocore\/awsservererror","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"AWSServerError","kind":"identifier"}],"navigatorTitle":[{"text":"AWSServerError","kind":"identifier"}],"kind":"symbol"}}}