{"metadata":{"role":"symbol","externalID":"s:8SotoCore14AWSServerErrorV15internalFailureACvpZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalFailure","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore14AWSServerErrorV","text":"AWSServerError","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Type Property","modules":[{"name":"SotoCore"}],"title":"internalFailure"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Linux"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailure"},{"kind":"text","text":": "},{"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","kind":"typeIdentifier","text":"AWSServerError","preciseIdentifier":"s:8SotoCore14AWSServerErrorV"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure"},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sotocore\/awsservererror\/internalfailure"]}],"kind":"symbol","sections":[],"references":{"doc://codes.soto.soto-core/documentation/SotoCore":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/sotocore","abstract":[{"type":"text","text":"The core framework for Soto, a Swift SDK for AWS"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","title":"SotoCore"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError/internalFailure":{"abstract":[],"url":"\/documentation\/sotocore\/awsservererror\/internalfailure","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalFailure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore14AWSServerErrorV","text":"AWSServerError"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError\/internalFailure","title":"internalFailure"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSServerError":{"role":"symbol","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSServerError","navigatorTitle":[{"kind":"identifier","text":"AWSServerError"}],"title":"AWSServerError","url":"\/documentation\/sotocore\/awsservererror","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSServerError"}]}}}