{"abstract":[{"type":"text","text":"additional context information related to the error"}],"metadata":{"externalID":"s:8SotoCore16AWSResponseErrorV7contextAA15AWSErrorContextVSgvp","role":"symbol","title":"context","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8SotoCore15AWSErrorContextV","text":"AWSErrorContext","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"SotoCore"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/codes.soto.soto-core\/documentation\/SotoCore","doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/context"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"context","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AWSErrorContext","kind":"typeIdentifier","preciseIdentifier":"s:8SotoCore15AWSErrorContextV","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["Linux"]}]}],"variants":[{"paths":["\/documentation\/sotocore\/awsresponseerror\/context"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSResponseError"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError","type":"topic","url":"\/documentation\/sotocore\/awsresponseerror","navigatorTitle":[{"kind":"identifier","text":"AWSResponseError"}],"abstract":[{"text":"Response Error type returned by Soto if the error code is unrecognised","type":"text"}],"title":"AWSResponseError","kind":"symbol"},"doc://codes.soto.soto-core/documentation/SotoCore":{"role":"collection","url":"\/documentation\/sotocore","kind":"symbol","title":"SotoCore","abstract":[{"text":"The core framework for Soto, a Swift SDK for AWS","type":"text"}],"type":"topic","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore"},"doc://codes.soto.soto-core/documentation/SotoCore/AWSErrorContext":{"title":"AWSErrorContext","url":"\/documentation\/sotocore\/awserrorcontext","type":"topic","abstract":[{"text":"Additional information about error","type":"text"}],"identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSErrorContext","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AWSErrorContext"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AWSErrorContext"}]},"doc://codes.soto.soto-core/documentation/SotoCore/AWSResponseError/context":{"title":"context","identifier":"doc:\/\/codes.soto.soto-core\/documentation\/SotoCore\/AWSResponseError\/context","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AWSErrorContext","preciseIdentifier":"s:8SotoCore15AWSErrorContextV"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/sotocore\/awsresponseerror\/context","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"additional context information related to the error"}]}}}